### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by crypt0inf0** [Piefayth/SHA256CUDA#3]
I get `terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid` error message.

**Comment by Piefayth** [comment]
You’re trying to mine fortuna? I wouldn’t bother right now - every miner is effectively unsupported until v2 launches. Nobody is mining - because it’s unprofitable - so we aren’t maintaining them.

Join the TxPipe discord, and once v2 launches someone will provide a functional / supported GPU miner. 

I’ll update the readme in this repo to be clear that it’s unmaintained for now.

**Comment by Piefayth** [comment]
Readme updated.
